Description:
  STU 01-Clo Pra11 - Lab 1.1.2 - Update of Lab 1.1.1 w/ parameter usage.
Parameters:
  BucketNameParam:
    Description: Bucket Name
    Type: String
Resources:
  LabBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: BucketNameParam

