Description:
  STU 01-Clo Pra12 - Lab 1.2.1 - IAM User and Managed Policy
Parameters:
  UserName:
    Description: IAM user name
    Type: String
    Default: labuser1
Resources:
  Policy1:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy for module 01-cloudformation Prectice 1.2 Lab 1.2.1
      ManagedPolicyName: stu-01clo-pra12-vlab121
      PolicyDocument:
        Version: 2012-10-17
        Statement: {
                     "Effect": "Allow",
                     "Action": [
                                 "s3:Get*",
                                 "s3:List*",
                                 "s3-object-lambda:Get*",
                                 "s3-object-lambda:List*"
                     ],
                     "Resource": "*"
        }
      Users:
        - !Ref UserName
  User1:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName