AWSTemplateFormatVersion: "2010-09-09"
Mappings:
  RegionMap:
    us-east-1:
      vpcId: vpc-da3c10bc
      subnetId: subnet-ec6f2c89
      imageId: ami-04169656fea786776
    us-east-2:
      vpcId: vpc-9aa942f3
      subnetId: subnet-8332c4ea
      imageId: ami-0552e3455b9bc8d50
    us-west-1:
      vpcId: vpc-0c00d304ac554a97f
      subnetId: subnet-05a1407456ad0c8e8
      imageId: ami-059e7901352ebaef8
    us-west-2:
      vpcId: vpc-8bc484f2
      subnetId: subnet-ebc60ca0
      imageId: ami-51537029
Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EC2LaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.nano
        IamInstanceProfile: 
          Name: !Ref InstanceProfile
        NetworkInterfaces:
          -
            DeviceIndex: 0
            AssociatePublicIpAddress: True
            SubnetId: !FindInMap [ RegionMap, !Ref "AWS::Region", subnetId ]
        UserData: 
          Fn::Base64: !Sub | 
            #!/bin/bash -xe
            # Install the files and packages from the metadata
            apt update -y
            apt install -y python-setuptools
            mkdir aws-cfn-bootstrap-latest
            curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
            easy_install aws-cfn-bootstrap-latest

            /usr/local/bin/cfn-init -v \
              --stack ${AWS::StackName} \
              --resource EC2 \
              --region ${AWS::Region}

            /usr/local/bin/cfn-signal -e $? \
              --stack ${AWS::StackName} \
              --resource EC2 \
              --region ${AWS::Region}
  EC2:
    Type: AWS::EC2::Instance
    Properties: 
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplate
        Version: "1"
      ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", imageId ]
    CreationPolicy:
      ResourceSignal:    
        Count: 1
        Timeout: PT5M
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          sources: 
            /etc/cloudwatchagent: https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
          commands:
            installCloudwatch: 
              command: ./install.sh
              cwd: /etc/cloudwatchagent
            launchCloudwatch: 
              command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref RoleCloudWatch
  RoleCloudWatch:
    Type: AWS::IAM::Role
    Properties: 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Topic 5 - EC2 Lab
      VpcId: !FindInMap [ RegionMap, !Ref "AWS::Region", vpcId ]
